version: '3.1' 

services:
  nginx-reverse-proxy-docker:
    image: openkbs/nginx-reverse-proxy-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-reverse-proxy-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - .env
    ports: # 8443 25901 26901 28080
      - 58080:8080   #  Proxy access 8000
    volumes:
      - ./etc/nginx:/etc/nginx
      
  UltraGraphQL-docker:
    container_name: UltraGraphQL-docker
    image: openkbs/UltraGraphQL-docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    gpus: all
    env_file:
      - ./.env
    environment:
      - CONTAINER_NAME=UltraGraphQL-docker
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      # - APP_HOME=${APP_HOME:-/home/developer/app}
      # - APP_MAIN=${APP_MAIN:-setup.sh}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-127.0.0.1}
      - DOCKER_HOST_NAME=${DOCKER_HOST_NAME:-localhost}
    ## -------------------------------------------
    ## -- Change to your specific Volumes Mapping:
    ## -------------------------------------------
    volumes:
      ## ==== Common mapping: ====
      - /etc/hosts:/etc/hosts
      - /dev/shm:/dev/shm
      #- /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./certificates:/home/developer/certificates
      ## ==== Use $HOME/data-docker as base directory: ====
      - $HOME/data-docker/UltraGraphQL-docker/data:/home/developer/data
      - $HOME/data-docker/UltraGraphQL-docker/workspace:/home/developer/workspace
      ## ==== Use current directory as root for mapping Volumes: ====
      ## (You need to manually create those child directory: ./data, ./workspace, and others)
      #- ./data:/home/developer/data
      #- ./workspace:/home/developer/workspace
      ## ==== App's additional mapping Volumes: ====
      - /home/user1/data-docker/ultragraphql-docker/data:/home/developer/data
      - /home/user1/data-docker/ultragraphql-docker/workspace:/home/developer/workspace

    ## -------------------------------
    ## -- Change to your specific port
    ## -------------------------------
    ports:
      - "48000:8000"

    ## -----------------------------
    ## -- Network setup if needed --
    ## -----------------------------
    # networks:
    #  - dev_network

#volumes:
#    UltraGraphQL-docker_volume:
#        external: false

#networks:
#  dev_network:
#    external:
#      name: dev_network


